# Nacos配置文件

# 全局配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: 
        group: DEFAULT_GROUP

# 用户服务配置
data-id: user-service.yaml
group: DEFAULT_GROUP
content: |
  server:
    port: 8081
    servlet:
      context-path: /
  
  spring:
    application:
      name: user-service
    datasource:
      url: jdbc:mysql://localhost:3306/open_platform_user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
    redis:
      host: localhost
      port: 6379
      password: 
      database: 1
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 1000ms
  
  # Nacos配置
  nacos:
    discovery:
      server-addr: localhost:8848
  
  # 日志配置
  logging:
    level:
      com.openplatform: debug
      org.springframework.web: debug
      org.hibernate.SQL: debug
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
      name: logs/user-service.log
  
  # 自定义配置
  open-platform:
    version: 1.0.0
    description: 用户服务